# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 14:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_no', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('students', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='author',
            name='age',
        ),
        migrations.AddField(
            model_name='author',
            name='city',
            field=models.CharField(default='Windsor', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='numpages',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='course',
            name='textbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Book'),
        ),
    ]
