# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20170521_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to='myapp.Student'),
        ),
    ]
