# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20170521_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='myapp.Author'),
        ),
        migrations.AlterField(
            model_name='course',
            name='textbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='myapp.Book'),
        ),
    ]
