# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.CharField(default='delhi', max_length=30),
        ),
    ]
