# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-29 04:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20170626_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='state',
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='Desktop/woman.jpg', upload_to='pics/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='numpages',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
